Create a demo app
jamesaoverton/cmi-pb-terminology pull request #53
Opened 2022-02-18 22:22 UTC by beckyjackson

To run the app:
1. Add the ontology table to the database using `make load_ontology` (`build/cmi-pb.db` does not need to exist first)
2. Set the Flask app - `export FLASK_APP=src/server/run.py`
3. Run using `flask run`

Some notes:
* multiprocessing is disabled in `load.py`
* every time you use `flask run`, the database is reloaded using the `load.py` script so changes aren't saved between sessions.
* this relies on the `gizmos` update here: https://github.com/ontodev/gizmos/pull/103

2022-02-20 00:23 UTC, lmcmicu requested changes

2022-02-20 00:23 UTC, lmcmicu commented on src/script/load.py
> +            results = OrderedDict()
Hi @beckyjackson I wonder if we could not push this change to the algorithm in `load.py` ~~for now~~ (i.e., the change which removes multiprocessing, from line 419-444), if that's alright? On the branch that I am working on I have made using multiprocessing configurable. If you could ~~wait for me to push that~~ undo this particular code change, and let me push my changes instead, that would be great and it would ~~lessen the chance of~~ not result in a merge conflict.

2022-02-20 00:23 UTC, lmcmicu commented on src/script/load.py
> +            results = OrderedDict()
Further to that, see [my own PR here](https://github.com/jamesaoverton/cmi-pb-terminology/pull/54) which has the changes to `load.py` that I mentioned above.

2022-02-20 00:23 UTC, lmcmicu commented on src/script/validate.py
> -def validate_existing_row(config, table_name, row, row_number):
~~Could you also undo this change to `validate_existing_row()` please? I have changed this function as well in the code that I am about to push in [this PR](https://github.com/jamesaoverton/cmi-pb-terminology/pull/54).~~

2022-02-20 00:23 UTC, lmcmicu commented on src/script/validate.py
> -def validate_existing_row(config, table_name, row, row_number):
~~Note: I realise that you needed it changed so as to call it on a not-existing row in `run.py`, but I would prefer to make the change in my PR if that's alright so as to avoid unnecessary merge conflicts.~~

2022-02-20 00:23 UTC, lmcmicu commented on src/script/validate.py
> -def validate_existing_row(config, table_name, row, row_number):
On second thought nevermind this comment on `validate_existing_row()`. Since my code replicates your changes exactly there will be no merge conflict.

2022-02-21 16:33 UTC, beckyjackson commented on src/script/load.py
> +            results = OrderedDict()
No problem, I removed this block of changes.

2022-02-21 16:39 UTC, lmcmicu commented on src/script/load.py
> +            results = OrderedDict()
Thanks!

2022-02-21 16:44 UTC, lmcmicu approved these changes

2022-02-22 16:35 UTC, merged